### ISSUE TITLE
PROD - Google Authentication

### ISSUE THREAD

**Issue by RobertSereny** [meca-technologies/Neural-Computation-for-Enhanced-Memory-Formation#1]
When I log into puretalk.ai using google Authentication, I receive spinning wheel and no entry . 

![Image](https://github.com/user-attachments/assets/4bc40857-1653-45af-8cd7-4359a48a3f42)

![Image](https://github.com/user-attachments/assets/2e09572a-dd64-4470-9444-5962af27a0de)

![Image](https://github.com/user-attachments/assets/476c30f9-c0b7-4622-ade3-b34b4869ba7e)

**Comment by RobertSereny** [comment]
New issue

When I reset my rob@brickandmortar, had issue per "PROD - Bug - Forget Password" bug as listed there. 
Then I got the below when trying to authenticate via Google Auth: 

![Image](https://github.com/user-attachments/assets/2ba15656-3d72-47ec-b901-0f4493539798)

![Image](https://github.com/user-attachments/assets/8ebc6e4c-0ed2-4454-a7e4-c1ead7b9c549)

**Comment by shamimferdous** [comment]
Resubmitted to Google for verification.
